# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f3f39826fa51bbd9c2be4d588a893705aa7d3a9fcb055cf70d635379e54e35ed7dd7f7f027f3e342d641c380c6caa44e758499a32c59efde569e83e368bfa7e

test:
  secret_key_base: c83fb7d2a94c1f65062c82cb5ec63961e8c23e12415c4e5bafd1ca8a2cc41b892151a714ab182af433e4b9125355c3def42c31edd3cdfd65bb719541cde6e2a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
